/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcCalc.h"

// função ADD
int *
add_100_svc(operandos *argp, struct svc_req *rqstp)
{
    static int  result;

//implementação do codigo
    //soma
    result = argp->x + argp->y;

    return &result;
}

// função SUB
int *
sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
    static int  result;

//implementação do codigo
    //suubtração
    result = argp->x - argp->y;

    return &result;
}

// função MUL
int *
mul_100_svc(operandos *argp, struct svc_req *rqstp)
{
    static int  result;

//implementação do codigo
    //multiplicação
    result = argp->x * argp->y;

    return &result;
}

// função DIV
int *
div_100_svc(operandos *argp, struct svc_req *rqstp)
{
    static int  result;
//implementação do codigo
    // divisão: COM TRATAMENTO DE DIVISÃO POR ZERO
    int y = argp->y;
    
    if (y == 0) {
        // Trata erro de divisão por zero retornando 0 (ou outro valor de erro)
        fprintf(stderr, "Servidor: Erro - Divisao por zero detectada.\n");
        result = 0; 
    } else {
        result = argp->x / y;
    }

    return &result;
}