/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcCalc.h"
#include <stdio.h>
#include <stdlib.h>

void prog_100(char *host) 
{
     //variaveis de entrada
    int x, y;
    int opcao;

    //ponteiro para estrutura do client rpc
    CLIENT *clnt; 
    //variaveis RPC de resultado e argumento (mantidas no padrao do rpcgen)
    int *result; //armazena o resultado da chamada
    operandos args; //armazenar os operandos

#ifndef DEBUG
    //funcao que estabelece a conexao rpc com protocolo udp
    clnt = clnt_create (host, PROG, VERSAO, "udp");
    
    //verificar erros: se clnt for NULL, conexao falhou
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif  // DEBUG

    while(1){ //loop
    // MENU INTERATIVO
    printf("\n     CLIENTE RPC");
    printf("\n---- CALCULADORA ----\n");
    printf("1. Soma (x + y)\n");
    printf("2. Subtração (x - y)\n");
    printf("3. Multiplicação (x * y)\n");
    printf("4. Divisão  (x / y)\n");
    printf("5. Sair\n");
    printf("Escolha a operação desejada: ");
    
    // VALIDAÇÃO DE ENTRADA - funcionando 
    if(scanf("%d", &opcao) != 1){ 
        printf("Opção inválida. Tente novamente.\n");
        while(getchar() != '\n'); //limpa burfferrrrr
        continue; //volta pro menu
    }
    
    // VALIDAÇÃO OPÇÃO
    if (getchar() != '\n') {
        printf("Opção inválida. Apenas números inteiros são aceitos para a opção.\n");
        while(getchar() != '\n'); 
        continue; 
    }

    //sair
    if(opcao == 5){
        printf("Encerrando o cliente...\n");
        break; //sai do loop
    }

    if(opcao >= 1 && opcao <= 4){
        //entradas x e y
        printf("Digite o primeiro numero [x]: ");
        if (scanf("%d", &x) != 1) { 
            printf("Entrada inválida. Apenas números inteiros são aceitos.\n");
            while(getchar() != '\n'); //limpa o buffer de erro
            continue; //volta para o menu
        }
        //limpeza
        if (getchar() != '\n') {
            printf("Entrada inválida. Apenas números inteiros (sem caracteres extras) são aceitos.\n");
            while(getchar() != '\n'); 
            continue; 
        }

        printf("Digite o segundo número [y]: ");
        if (scanf("%d", &y) != 1) { 
            printf("Entrada inválida. Apenas números inteiros são aceitos.\n");
            while(getchar() != '\n'); 
            continue; 
        }
        //limpeza
        if (getchar() != '\n') {
            printf("Entrada inválida. Apenas números inteiros (sem caracteres extras) são aceitos.\n");
            while(getchar() != '\n'); 
            continue;
        }

		//preenche struct de argumentos usada pelo RPC
        args.x = x;
        args.y = y;
        result = NULL;
        
        //chamando funcoes
        switch(opcao){
            case 1:
                result = add_100(&args, clnt);
                break;
            case 2:
                result = sub_100(&args, clnt);
                break;
            case 3:
                result = mul_100(&args, clnt);
                break;
            case 4:
                result = div_100(&args, clnt);
                break;
        }
        // ... (Verificação de resultado e printf)

     if (result == (int *) NULL){
                clnt_perror(clnt, "RPC falhou."); 
                //funcao que consulta clnt
            } else{
                printf("Resultado do servidor: %d\n", *result);
            }
        } else{
            printf("Opcao invalida. Tente novamente.\n");
        }
} // fecha while

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif
}

int
main (int argc, char *argv[])
{
	//argc contagem de argumentos
    //argv array de string com argumento
    char *host;

    //garante que o usuario forneceu pelo menos um argumento
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
    host = argv[1]; //armazena o primeiro arguemento
    prog_100 (host); //chama a função principal
exit (0);
}